---
- name: Playbook to create gce load balancing instance
  hosts: localhost
  connection: local
  gather_facts: No

  vars:
    service_account_email: webon123@ansible-proyect.iam.gserviceaccount.com
    credentials_file: ansible-proyect-8923da4c188d.json
    project_id: ansible-proyect
    instance_names: web3,web4,web6
  tasks:
    - name: Delete gce load balancer
      gce_lb:
        name: lbserver
        state: absent
        region: us-east1
        members: ['us-east1-b/web3','us-east1-b/web4','us-east1-b/web5']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
    - name: Delete firewall rule to allow http traffic
      gce_net:
        name: default
        fwname: "my-http-fw-rule"
        allowed: tcp:80
        state: absent
        src_range: "0.0.0.0/0"
        target_tags: "http-server"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
    - name: Delete an instance based on image {{ image }}
      gce:
        zone: us-east1-b
        instance_names: "{{ instance_names }}"
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

